name: test-workflow
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  build-backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install
        working-directory: ./backend
        run: yarn

      - name: Build backend
        working-directory: ./backend
        run: npx tsc

      - name: Test secret
        run: echo ${{ secrets.TEST }}

      - name: Rsync built backend
        working-directory: ./backend
        run: rsync -avz ./dist/ web@${{ secrets.SSH_HOST }}:test/dist

      - name: Rsync node modules
        working-directory: ./backend
        run: rsync -avz ./node_modules/ web@${{ secrets.SSH_HOST }}:test/node_modules
